### ISSUE TITLE
[1.20.1] Compatibility issue with All the Trims

### ISSUE THREAD

**Issue by druidicmage** [AverageAnime/create-food-1.20.1#10]
Enabling the optional food options in the config causes the client to be unable to join the server when All the Trims is installed.

https://mclo.gs/9cHpqSa

**Comment by AverageAnime** [comment]
Are you enabling the items in both the server and client config or just the client? And restarting both after?

**Comment by druidicmage** [comment]
Is it required to be changed on the config clientside as well? I'm using a dedicated server.

**Comment by AverageAnime** [comment]
Yes, the config needs to be changed on the server side and client side.

**Comment by druidicmage** [comment]
I see. Is this planned to be changed?

**Comment by AverageAnime** [comment]
No, is that an issue? Are you unable to make the config files match?

**Comment by druidicmage** [comment]
No, I can, it's just inconvenient is all. It's not just me playing on the server, and I only give the players the mod list.

**Comment by AverageAnime** [comment]
I suppose I could change the config file to default to enable all the optional food items, but I think it makes more sense to have the optional stuff be disabled by default since I don't want to presume what additional mods people are using. I'll be adding a lot more optional food items related to other mods, so if I did change the config to have everything enabled, you would still have to make sure everyone is using the same config if you want to disable any of them.
