### ISSUE TITLE
Cheese recipe doesn't give bucket back

### ISSUE THREAD

**Issue by NolanHewitt** [AverageAnime/create-food-1.20.1#13]
The cheese recipe using a mixer requires a milk bucket item instead of milk liquid, so that it doesn't overlap with the butter recipe which is understandable. However, the cheese recipe doesn't give the empty milk bucket item back. IMO the best option would be to change the recipe to use milk liquid and something other than salt, but if not it should at least return an empty bucket. Or perhaps the recipes could be changed to accept c:milks so milk powder could be used instead.

**Comment by AverageAnime** [comment]
This mod doesn't add a mixing recipe for cheese, just a compacting recipe + a cooking recipe.  I assume you are using another mod that generates mixing recipes based on cooking recipes. Not getting an empty bucket back presumably has more to do with that mod than mine.

In regards to the tag used in the recipe, I can't change it to c:milks because that still overlaps with butter. The milk bottle is also tagged with c:milks, so if you try and make butter with a milk bottle and salt, you get a cheese block.
So instead, I recommend adding milk powder to the c:milk_buckets tag so it can be used in the cheese cooking recipe. This'll be in the next update.
