### ISSUE TITLE
block image error

### ISSUE THREAD

**Issue by banya457** [AverageAnime/create-food-1.20.1#2]
'Light Blue Gelatin Dessert Block' I installed it and it appears as an error block.

**Comment by AverageAnime** [comment]
Thank you for the report. 
The issue is a missing .json that belongs in assets\createfood\blockstates. 
I have fixed it for the next release (1.0.3), but you can fix the current version by taking this [file](https://github.com/AverageAnime/create-food/blob/1.20.1/src/main/resources/assets/createfood/blockstates/light_blue_gelatin_dessert_block.json) and placing it in the blockstates folder.
