### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by Axe555** [AverageAnime/create-food-1.20.1#3]
crash log:
https://paste.ee/p/54Jen

**Comment by AverageAnime** [comment]
Hi, I wasn't able to replicate the crash, but I did get datapack errors. I believe the issue is the tags used in two files. Use the two .json files below (or just edit/delete the ones in the mod) and that should work. 

sugar_cookie_from_campfire.json from https://github.com/AverageAnime/create-food/blob/1.20.1/src/main/resources/data/createfood/recipes/minecraft/campfire/sugar_cookie_from_campfire.json
and snickerdoodle_from_campfire.json from https://github.com/AverageAnime/create-food/blob/1.20.1/src/main/resources/data/createfood/recipes/minecraft/campfire/snickerdoodle_from_campfire.json
