### ISSUE TITLE
Server Log Errors still on 1.1.4

### ISSUE THREAD

**Issue by null15** [AverageAnime/create-food-1.20.1#40]
Log: https://mclo.gs/Q2ukDfL

**Comment by AverageAnime** [comment]
Ok, so I believe the reason why these errors appear is because you have Cultural Delight and Ube's Delight, but several of the optional items from this mod are disabled. Enabling the items will get rid of the errors. If you don't want the optional items, you should be able to use a datapack to overwrite the recipes and loot tables that cause the errors.
