### ISSUE TITLE
Log spam and warnings

### ISSUE THREAD

**Issue by PaulRV0709** [AverageAnime/create-food-1.20.1#6]
When using the mod, the log gets spammed with these statements
![image](https://github.com/AverageAnime/create-food/assets/82379138/e619951d-7f6c-4b56-9033-e68aa1e0b66c)
I looked online and it might have something to do with comments in a JSON file, but idk. Please fix this as log spam makes it hard to debug other things.

**Comment by AverageAnime** [comment]
Fixed in next release. 
Fix can be applied to previous versions by adding the JSONs found here:
https://github.com/AverageAnime/create-food/tree/1.20.1/src/main/resources/assets/createfood/blockstates
and 
https://github.com/AverageAnime/create-food/tree/1.20.1/src/main/resources/assets/createfood/models/block
